name: Deploy Server To Heroku

on:
  push:
    paths:
      - 'server/**/*.*'

jobs:
  deploy_client:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Heroku login credentials
        run: |
          cat > ~/.netrc <<EOF
            machine api.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
            machine git.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
          EOF
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
      - name: Deploy server
        run: |
          heroku git:remote -a $HEROKU_SERVER_APP_NAME
          git push heroku main
        env:
          HEROKU_SERVER_APP_NAME: ${{ secrets.HEROKU_SERVER }}